name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_lualatex: true
      - name: Move PDF file to repository
        run: mv main.pdf $GITHUB_WORKSPACE/main.pdf
      - name: Commit PDF file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add main.pdf
          git commit -m "Add main.pdf"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
