name: Compile and Deploy CV

on:
  push:
    branches: [develop]
  workflow_dispatch:

env:
  LATEX_MAIN: "cv.tex"          # Nom de votre fichier LaTeX principal
  CV_NAME: "MyProfessionalCV"   # Nom de base souhaité pour le PDF
  TIMEZONE: "Europe/Paris"      # Fuseau horaire

permissions:
  contents: write

jobs:
  compile:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest
      options: --env TZ=${{ env.TIMEZONE }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set container timezone
        run: |
          ln -sf /usr/share/zoneinfo/$TZ /etc/localtime
          echo $TZ > /etc/timezone

      - name: Compile LaTeX
        run: |
          latexmk -pdf -lualatex="lualatex -interaction=nonstopmode" $LATEX_MAIN

      - name: Generate UTC timestamp
        id: timestamp
        run: |
          BUILD_TIME=$(date -u +'%Y%m%dT%H%M%SZ')
          echo "build_time=$BUILD_TIME" >> $GITHUB_OUTPUT
          echo "PDF_NAME=${LATEX_MAIN%.*}-$BUILD_TIME.pdf" >> $GITHUB_ENV

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdf
          path: ${{ env.LATEX_MAIN%.* }}.pdf

  deploy:
    needs: compile
    runs-on: ubuntu-22.04
    env:
      TZ: ${{ env.TIMEZONE }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: cv-pdf
          path: ./artifacts

      - name: Setup files
        run: |
          mkdir -p out
          TIMESTAMP=${{ needs.compile.outputs.build_time }}
          mv ./artifacts/${LATEX_MAIN%.*}.pdf "./out/$CV_NAME-$TIMESTAMP.pdf"

      - name: Generate preview
        run: |
          convert -density 300 -background white -alpha remove \
          "./out/$CV_NAME-${{ needs.compile.outputs.build_time }}.pdf[0]" \
          -resize 25% \
          -quality 75 \
          preview.jpg

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ needs.compile.outputs.build_time }}"
          name: "CV Version ${{ needs.compile.outputs.build_time }}"
          files: |
            ./out/$CV_NAME-${{ needs.compile.outputs.build_time }}.pdf
            preview.jpg

      - name: Update repository
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add preview.jpg
          git commit -m "Update CV preview [skip ci]"
          git push